apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world
        image: 066283105853.dkr.ecr.us-east-2.amazonaws.com/ateb-hackathon-demo:latest
        ports:
        - name: http-port
          containerPort: 80
